// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PizzaStoreV3.Data;

#nullable disable

namespace PizzaStoreV3.Migrations
{
    [DbContext(typeof(PizzaDb))]
    [Migration("20241226112111_InitialMigrate")]
    partial class InitialMigrate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("PizzaStoreV3.Model.Pizza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pizzas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Pizza shaped like a great mountain",
                            Name = "Montemagno"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Pizza shaped like a submarine, silent but deadly",
                            Name = "The Galloway"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Pizza shaped like a Viking helmet, where's the mead",
                            Name = "The Noring"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
