// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PizzaStoreV1.Data;

#nullable disable

namespace PizzaStoreV1.Migrations
{
    [DbContext(typeof(PizzaDb))]
    partial class PizzaDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("PizzaStoreV1.Model.Pizza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pizzas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Pizza shaped like a great mountain",
                            Name = "Montemagno"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Pizza shaped like a submarine, silent but deadly",
                            Name = "The Galloway"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Pizza shaped like a Viking helmet, where's the mead",
                            Name = "The Noring"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
