// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PizzaStoreV2.Data;

#nullable disable

namespace PizzaStoreV2.Migrations
{
    [DbContext(typeof(PizzaDb))]
    partial class PizzaDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.1.24081.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PizzaStoreV2.Model.Pizza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Pizzas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Pizza shaped like a great mountain",
                            Name = "Montemagno"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Pizza shaped like a submarine, silent but deadly",
                            Name = "The Galloway"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Pizza shaped like a Viking helmet, where's the mead",
                            Name = "The Noring"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
