# Jaeger v2 all-in-one configuration
# This configuration sets up Jaeger to receive OTLP data and store it in memory

extensions:
  jaeger_query:
    storage:
      traces: memory_storage
    grpc:
      endpoint: "0.0.0.0:16685"
    http:
      endpoint: "0.0.0.0:16686"

  jaeger_storage:
    backends:
      memory_storage:
        memory:
          max_traces: 50000

  remote_sampling:
    file:
      path: ""
      default_sampling_probability: 1
      reload_interval: 1s
    http:
      endpoint: "0.0.0.0:5778"
    grpc:
      endpoint: "0.0.0.0:5779"

  healthcheckv2:
    use_v2: true
    http:
      endpoint: "0.0.0.0:13133"

  expvar:
    endpoint: "0.0.0.0:27777"

  zpages:
    endpoint: "0.0.0.0:27778"

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

  jaeger:
    protocols:
      grpc:
        endpoint: "0.0.0.0:14250"
      thrift_http:
        endpoint: "0.0.0.0:14268"
      thrift_binary:
        endpoint: "0.0.0.0:6832"
      thrift_compact:
        endpoint: "0.0.0.0:6831"

  zipkin:
    endpoint: "0.0.0.0:9411"

processors:
  batch:

exporters:
  jaeger_storage_exporter:
    trace_storage: memory_storage

service:
  extensions: [jaeger_storage, jaeger_query, remote_sampling, healthcheckv2, expvar, zpages]
  pipelines:
    traces:
      receivers: [otlp, jaeger, zipkin]
      processors: [batch]
      exporters: [jaeger_storage_exporter]
